### ISSUE TITLE
使用时遇到错误：ERROR in ./~/.0.20.0@cheerio/index.js

### ISSUE THREAD

**Issue by sinchang** [egoist/get-instagram-photo#1]
你好，使用中遇到如下错误是怎么回事?项目是使用vue-cli。
![screenshot](https://cloud.githubusercontent.com/assets/3297859/17483606/5bff6f36-5db9-11e6-8b54-07808ac4f8ad.png)
![get instagram photo](https://cloud.githubusercontent.com/assets/3297859/17483655/82bc59ae-5db9-11e6-9344-4f79e026ecac.png)

**Comment by egoist** [comment]
这个 package 只能 node 使用

**Comment by egoist** [comment]
客户端使用最好放在一个 API 服务器上然后请求返回响应的图片地址

**Comment by sinchang** [comment]
@egoist OK 谢谢

**Comment by egoist** [comment]
👋🏻

**Comment by egoist** [comment]
做了个 API server https://github.com/egoist/instagram-photo-api
